name: Morning Bot

on:
  workflow_dispatch:
  schedule:
    # 这里的 cron 分别对应北京时间的 12:15, 20:15, 07:15
    - cron: '20 4 * * *'
    - cron: '15 12 * * *'
    - cron: '15 23 * * *'

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装必要库
        run: pip install requests

      - name: 运行脚本
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          TIAN_KEY: ${{ secrets.TIAN_KEY }}
        run: python main.py
