name: Morning Bot

on:
  workflow_dispatch:      # 手动触发按钮
  schedule:               # 定时触发
    - cron: '15 4 * * *'  # 12:15推送，注意横杠前有空格
    - cron: '15 12 * * *' # 20:15推送
    - cron: '15 23 * * *' # 07:15推送
  

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 检出代码
        uses: actions/checkout@v3

      - name: 安装 Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: 安装必要库
        run: pip install requests

      - name: 运行脚本
        env:
          BARK_KEY: ${{ secrets.BARK_KEY }}
          WEATHER_KEY: ${{ secrets.WEATHER_KEY }}
          TIAN_KEY: ${{ secrets.TIAN_KEY }}
        run: python main.py morning
